// Generated by CoffeeScript 1.6.3
(function() {
  var name, sayHi, string,
    __slice = [].slice;

  name = 'eiji';

  string = "hello, " + (name || 'eiji');

  sayHi = function() {
    var name, others, three, _i;
    name = arguments[0], others = 3 <= arguments.length ? __slice.call(arguments, 1, _i = arguments.length - 1) : (_i = 1, []), three = arguments[_i++];
    if (name == null) {
      name = 'eiji';
    }
    if (three == null) {
      three = '3rd';
    }
    console.log("name = " + name);
    console.log("others = " + others);
    console.log("name = " + three);
    return name + others + three;
  };

  sayHi(1, 2, 3, 4, 5);

}).call(this);

/*
//@ sourceMappingURL=coffeeTest.map
*/
